### ISSUE TITLE
Remove Visual Studio Cache directory

### ISSUE THREAD

**Issue by JuDelCo** [pixelatto/Atto#1]
".vs" folder should be removed from project.

https://www.gitignore.io/api/visualstudio

**Comment by JaviCepa** [comment]
Lo tenía comiteado antes de añadir el gitignore, por eso seguía ahí >_<
Ya está arreglado :)

**Comment by JuDelCo** [comment]
Always reference the fix commit

Commit ccb61b0 closes #1
