### ISSUE TITLE
AttoSettingsProvider is binded two times after generating AttoAccess.cs

### ISSUE THREAD

**Issue by JuDelCo** [pixelatto/Atto#2]
https://github.com/pixelatto/atto/blob/99b6b5cfc32f9923751edec64e6620d6ffdc4146/Editor/AttoAccessBuilder.cs#L147

**Comment by JaviCepa** [comment]
Fixed

**Comment by JuDelCo** [comment]
Always reference the fix commit

Commit 8350d14 closes #2
