### ISSUE TITLE
Dynamic and Static attributes in ServiceCaching works the same way.

### ISSUE THREAD

**Issue by JuDelCo** [pixelatto/Atto#3]
https://github.com/pixelatto/atto/blob/99b6b5cfc32f9923751edec64e6620d6ffdc4146/Runtime/BindServiceAttribute.cs#L21

https://github.com/pixelatto/atto/blob/99b6b5cfc32f9923751edec64e6620d6ffdc4146/Editor/AttoAccessBuilder.cs#L177

https://github.com/pixelatto/atto/blob/99b6b5cfc32f9923751edec64e6620d6ffdc4146/Editor/AttoAccessBuilder.cs#L183

**Comment by JuDelCo** [comment]
In other words, all Services with Dynamic attribute are Static as well.

**Comment by JaviCepa** [comment]
No entiendo lo que quieres decir aquí.
El dinámico resuelve siempre el getter del core,
el estático cachea el valor el inicio y luego devuelve siempre ese.

**Comment by JuDelCo** [comment]
The container always returns the same reference per service provider, so it's the same as "Static" as you implemented it.

**Comment by JaviCepa** [comment]
Removed caching modes feature

**Comment by JuDelCo** [comment]
Commit e1f66d2 closes #3
