### ISSUE TITLE
Project won't compile if a service provider was renamed or deleted (AttoAccess.cs Helper)

### ISSUE THREAD

**Issue by JuDelCo** [pixelatto/Atto#5]
If in any point of the project development, there is an compiler error AND a service provider was deleted or renamed, the project will never compile until fix manually the references in AttoAccess.cs (that file is autogenerated and shouldn't be touched manually).

Workarounds / Solutions:
- Generate code using reflection with Rosyln.
- Don't autogenerate code (switch to another approach).
- Live with this issue forever and let the users need to fix manually that file on refactors or deletions (and that conflicts with the whole idea of that file being autogenerated on first place).

😬

**Comment by JaviCepa** [comment]
No es lo más elegante, pero borrando AttoAccess y recompilando volvería a funcionar (si te he entendido bien) no?

**Comment by JaviCepa** [comment]
Por ahora he desactivado la auto-generación de AttoAccess.
Hay que invocarla desde el menú "tools" hasta nueva solución.

**Comment by JuDelCo** [comment]
> No es lo más elegante, pero borrando AttoAccess y recompilando volvería a funcionar (si te he entendido bien) no?

No, if you delete AttoAccess.cs thinking to rebuild it from scratch won't work because code will use Helpers (Core.ProvideName.SomeMethod...) and there will be errors everywhere.

**Comment by JaviCepa** [comment]
Ok, you mean if I rename some service provided by a new package version right?
User-generated services (source files inside the assets folder) shouldn't have this problem if I understand correctly.

**Comment by JuDelCo** [comment]
> Ok, you mean if I rename some service provided by a new package version right?
> User-generated services (source files inside the assets folder) shouldn't have this problem if I understand correctly.

In either case, if users delete OR rename/refactor a custom service provider, users must edit manually the file or compilation will fail.

It's true that if the refactor is made using a IDE tool, that is less harsh (but anyway file was modified by them, not by the generator).

And yes, you are locked to the names you choose for the provided services in this package, the autogenerated file is outside of it, you can't overwrite it with a package update.

**Comment by JaviCepa** [comment]
Manual generation it is, for now.

**Comment by JuDelCo** [comment]
> Manual generation it is, for now.

This issue should be stay **open** then, as this is a problem users will face.

If the issue is closed it won't be visible and will be more confused for the people. If stays open, they can research their problems, suggests more solutions here or even read about it beforehand.
